#!/bin/bash

set -e

function print_usage() {
	echo "$(basename $0)"
	echo ""
	echo "usage:"
	echo ""
	echo "$(basename $0) [options]"
	echo ""
	echo "Options:"
	echo " -h                          print this help text"
	echo " -i [basename],[numnodes]    generate/update inventory file"
	echo " -s                          skip host update/upgrade and reboot"
	echo " -w                          wipe all src/build dirs and start fresh"
	echo " -l [src options see below]  libqb"
	echo " -k [src options see below]  kronosnet"
	echo " -c [src options see below]  corosync"
	echo " Source options: (default git, github repos, master branch)"
	echo "    git[,repo[,branch]]      use git. Optionally provide an alternative repo and branch"
	echo "                             brach accepts the same values as defined by:"
	echo "                             http://docs.ansible.com/ansible/git_module.html version option"
	echo "                             with force = yes"
	echo "    local,path               path to the code. Code must be initializied"
	echo "                             and directory should already contains ./configure"
	echo "    system                   install system provided rpms"
	echo "    skip                     do nothing. code is installed already. don't touch it"
}

function generate_ansible_cfg {
	echo "[defaults]" > ansible.cfg
	echo "callback_plugins = plugins/" >> ansible.cfg
	echo "inventory = ansible-inventory" >> ansible.cfg
	echo "generated ansible config:"
	echo "========================="
	cat ansible.cfg
	echo "========================="
	echo ""
}

function generate_inventory_file() {
	echo "[test-nodes]" > ansible-inventory
	echo "$knethosts" | sed -e 's/,/[1:/g' -e 's/$/]/g' >> ansible-inventory
	echo "generated ansible inventory:"
	echo "============================"
	cat ansible-inventory
	echo "============================"
	echo ""
}

function parse_src_opts {
	project="$1"
	shift
	args="$@"

	src="$(echo $args | awk -F ',' '{print $1}')"

	case "$src" in
		system)
			extravars="${project}src=system $extravars"
		;;
		skip)
			extravars="skip$project=yes $extravars"
		;;
		git)
			extravars="${project}src=git $extravars"
			repo="$(echo $args | awk -F ',' '{print $2}')"
			if [ -n "$repo" ]; then
				extravars="${project}gitrepo=$repo $extravars"
				version="$(echo $args | awk -F ',' '{print $3}')"
				if [ -n "$version" ]; then
					extravars="${project}gitver=$version $extravars"
				fi
			fi
		;;
		local)
			extravars="${project}src=local $extravars"
			localpath="$(echo $args | awk -F ',' '{print $2}')"
			if [ -z "$localpath" ]; then
				echo "Error: $project local option requires a path to the src code"
				exit 1
			fi
			extravars="${project}localpath=$localpath $extravars"
		;;
		*)
			echo "Unknown $src option for $project"
			exit 1
		;;
	esac

	return 0
}

# parse command line options

extravars=""

while getopts ":hi:swl:k:c:" optflag; do
	case "$optflag" in
	i)
		knethosts="$OPTARG"
		;;
	h)
		print_usage
		exit 0
		;;
	s)
		extravars="skipupdate=yes $extravars"
		;;
	w)
		extravars="wipecode=yes $extravars"
		;;
	l)
		parse_src_opts libqb "$OPTARG"
		;;
	k)
		parse_src_opts kronosnet "$OPTARG"
		;;
	c)
		parse_src_opts corosync "$OPTARG"
		;;
	\?|:)
		print_usage
		exit 1
		;;
	esac
done

if ! which ansible >/dev/null 2>&1; then
	echo "ERROR: missing ansible binary from PATH"
	exit 1
fi

if ! which ansible-playbook >/dev/null 2>&1; then
	echo "ERROR: missing ansible-playbook binary from PATH"
	exit 1
fi

# automatic update ansible-config
if [ -f ansible.cfg.manual ]; then
	cp ansible.cfg.manual ansible.cfg
else
	generate_ansible_cfg
fi

# generate and check ansible inventory file
if [ -n "$knethosts" ]; then
	generate_inventory_file
fi
if [ ! -f ansible-inventory ]; then
	echo "ERROR: missing ansible-inventory file"
	exit 1
fi

echo "Checking connectivity to nodes"
echo ""

ansible all -m ping || exit 1
echo ""

ansible-playbook site.yml --extra-vars "$extravars"

exit 0
